import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "내 사이트",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header>
          <nav className="flex gap-4">
            <Link href="/">메인</Link> {/* a 태그와 동일한 기능을 함. 그러나 더 빠름 */}
            <Link href="/posts">post</Link>
            
          </nav>
        </header>
        <main className="flex-1 flex justify-center items-center">{children}</main>
        <footer>푸터</footer>
      </body>
    </html>
  );
}
